---
title: "Exercise 1 Plots"
author: "Dustin Haraden"
date: "February 22, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r library}
library(tidyverse)
library(psych)
library(rmdrive) #https://github.com/ekothe/rmdrive
library(dataMaid)
library(sjPlot)



dep <- read.csv('Data/depress.csv')

#clean(dep)
#describe(dep$hob)


```


```{r histogram}
ggplot(dep, aes(hob)) +
  geom_histogram(binwidth = 2)
```

#Google Drive library(rmdrive)
write plain text 
Here I am adding something on google drive

```{r Google Drive}

#To install
  #devtools::install_github("ekothe/rmdrive")

#Upload Markdown to Google Drive (Step 1)
  #upload_rmd(file = 'markdown_name', gfile = 'googledrive_name')

#Update the existing file in google drive with what you have in your markdown
  #update_rmd(file = 'markdown_name', gfile = 'googledrive_name')

#Download ("pull") the file from Google drive to work on in R
  #download_rmd(file = 'markdown_name', gfile = 'googledrive_name')

```

#RMarkdown 
  https://bookdown.org/yihui/rmarkdown/ 
  
```{r Markdown stuff}
mean_h <- round(mean(dep$dep19, na.rm=T), 3)
```

Mean of our **hobbies** was `r mean_h`

Mean of hobbies variable is `r round(mean(dep$dep19, na.rm=T), 3)`

#Tables

sjPlot -> http://www.strengejacke.de/sjPlot/
  Correlations -> http://www.strengejacke.de/sjPlot/reference/sjt.corr.html 
  
stargazer -> https://www.jakeruss.com/cheatsheets/stargazer/ 

xtable -> https://www.rdocumentation.org/packages/xtable/versions/1.8-3/topics/xtable

```{r correlation}
#Full Correlation
sjt.corr(dep)

#Selected Variables
  dep %>% 
    select('sex','grade','hob','dep1':'dep5') %>% 
    sjt.corr()
  
  
#Pretty Tables
  dep %>% 
    select('sex','grade','hob','dep1':'dep5') %>% 
    sjt.corr(show.p=FALSE,digits=2, triangle='upper', 
             string.diag = c('1','2','3','4','5','6','7','8'),
             file = 'Tables/Table1.html')
  
  #dplyr::rename_all('Gender','Grade','Hobbies','Depression-1','Depression-2',
  #         'Depression-3','Depression-4','Depression-5') %>% 
```

Table 1 Correlation

`r sjt.corr(dep)` 